import Header from './components/Header'
import ThirdwebProviderLayer from './components/ThirdwebProviderLayer'
import './globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className=''>
        <ThirdwebProviderLayer>
          <Header />
          {children}
        </ThirdwebProviderLayer>
        
      </body>
    </html>
  )
}
